### ISSUE TITLE
In Chapter 2 - Exercise 3, the description of the Exercise does not match the solution

### ISSUE THREAD

**Issue by urlgirl** [Damonlee92/Build_Your_Own_AI_Investor_2021#1]
The description of Exercise 3 is:
`# Output stocks with a price/earnings ratio below a number and a beta above a number. `
`# return a list of aceptable stocks with ascending by P/E`

The function 'filterStocks' actually differs from the description in two ways:

- It tests for beta _below_ a number, not above;
- It doesn't sort the acceptable stocks ascending by P/E

**Comment by Damonlee92** [comment]
Changed description code comment. 

Many thanks.
